from typing import Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Input payload validation model for initiating or continuing chats."""

    message: str = Field(..., min_length=1, max_length=10000, description="The user message to process")
    conversation_id: Optional[str] = Field(None, description="Optional UUID tracking conversation history")


class ChatResponse(BaseModel):
    """Output serialization model containing generated response metadata."""

    response: str = Field(..., description="Decoded textual response generated by the AI")
    conversation_id: str = Field(..., description="Conversation UUID tracking thread")
    timestamp: float = Field(..., description="Epoch timestamp of generation")
    provider: str = Field(..., description="Underlying provider service answering request")
    model: str = Field(..., description="Name of LLM employed")
    tokens_used: int = Field(..., description="Approximated tokens consumed")


class AIHealthSchema(BaseModel):
    """Status reporting model for AI sub-systems."""

    status: str = Field(..., description="Availability status of the selected provider")
    provider: str = Field(..., description="Active system AI provider")
    default_model: str = Field(..., description="Default configuration model name")
